In [1]:
import numpy as np
import timeit

In [2]:
# Porównanie szybkoci wykonania zadania:

t1 = timeit.Timer("[math.sin(i) for i in range(10000)]","import math") # działanie na pojedyńczym elemencie obiektu
czas1 = t1.timeit(number=1000)
print("Czas wykonania pierwszego kodu wynosi:",round(czas1,4),"sekund.\n")

t2 = timeit.Timer("np.sin(np.arange(10000))","import numpy as np") # działanie na całym obiekcie
czas2 = t2.timeit(number=1000)
print("Czas wykonania drugiego kodu wynosi:",round(czas2,4),"sekund.\n")

Czas wykonania pierwszego kodu wynosi: 3.4569 sekund.

Czas wykonania drugiego kodu wynosi: 0.6713 sekund.



In [3]:
x = np.array([0,1,2,3,4,5]) # wektor szescioelementowy
x1 = x.ndim                 # wymiar tablicy x
x2 = x.shape                # N-elementowa krotka okreslajaca rozmiar dla kazdego wymiaru
x3 = x.size                 # liczba wszystkich elementow
x4 = len(x)                 # liczba elementow w pierwszym wymiarze
x5 = x.dtype

print("Wektor:", x ,"ma wymiar:", x1 ,"i ksztalt:", x2 , end=".")
print("Liczba wszystkich jego elementow wynosi:",x3,"a liczba elementow w pierwszym wymiarze:",x4,end=".\n")
print("Typ danych: ", x5)

Wektor: [0 1 2 3 4 5] ma wymiar: 1 i ksztalt: (6,).Liczba wszystkich jego elementow wynosi: 6 a liczba elementow w pierwszym wymiarze: 6.
Typ danych:  int64


In [4]:
# Analogicznie jak wyżej dla macierzy

A = np.array([(1,2,3),(4,5,6),(7,8,9)])
a1 = A.ndim
a2 = A.shape
a3 = A.size
a4 = len(A)
a5 = A.dtype

print("Macierz:", A ,"ma wymiar:", a1 ,"i ksztalt:", a2 , end=".")
print("Liczba wszystkich jej elementow wynosi:",a3,"a liczba elementow w pierwszym wymiarze:",a4,end=".\n")
print("Typ danych: ", a5)

Macierz: [[1 2 3]
 [4 5 6]
 [7 8 9]] ma wymiar: 2 i ksztalt: (3, 3).Liczba wszystkich jej elementow wynosi: 9 a liczba elementow w pierwszym wymiarze: 3.
Typ danych:  int64


konwersja

In [27]:
A = A.astype(np.float64);A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

lista vs array

In [18]:
text = "analiza id"

In [19]:
text_list = [ord(x) for x in text]; text_list

[97, 110, 97, 108, 105, 122, 97, 32, 105, 100]

In [20]:
text_array = np.array(text_list); text_array

array([ 97, 110,  97, 108, 105, 122,  97,  32, 105, 100])

In [21]:
text_list * 2

[97,
 110,
 97,
 108,
 105,
 122,
 97,
 32,
 105,
 100,
 97,
 110,
 97,
 108,
 105,
 122,
 97,
 32,
 105,
 100]

In [22]:
text_array * 2

array([194, 220, 194, 216, 210, 244, 194,  64, 210, 200])

lista w czasie mnozenia podwoila ilosc swoich elemnetow. Array jest zwektoryzowany, dlatego zostala pomnozona wartosc jego elementow. Aby uzyskac taki wynik w przypadku list nalezy uzyc list comprehension [x * 2 for x in text_list] - ma to jednak wplyw na wydajnosc

In [25]:
B = text_array.reshape(2,5)         # zmiana kształtu tablicy
print(B,"\n")
C = B.ravel()              # zmiana tablicy na wektor
print(C,"\n")
Cl = C.tolist()            # konwersja na liste
print(Cl,"\n")

[[ 97 110  97 108 105]
 [122  97  32 105 100]] 

[ 97 110  97 108 105 122  97  32 105 100] 

[97, 110, 97, 108, 105, 122, 97, 32, 105, 100] 



In [24]:
# Kilka specjalnych macierzy

print(np.arange(1,5,0.5),"\n")           # ciag liczb od 1 do 5 (bez 5) z krokiem 0.5

[1.  1.5 2.  2.5 3.  3.5 4.  4.5] 



In [ ]:
print(np.linspace(1,6,6),"\n")           # ciag arytmetyczny liczb z przedzialu od 1 do 6 o dlugosci 6

In [ ]:
print(np.eye(3),"\n")                    # macierz jednostkowa  
print(np.eye(3,dtype = np.bool_),"\n")   # jak wyzej ale z okreslonym typem elementow

In [ ]:
print(np.diag([1,7,9]),"\n")             # macierz diagonalna

In [ ]:
print(np.zeros((4,5)),"\n")              # macierz zerowa

In [21]:
print(np.ones((5,5)),"\n")               # macierz wypelniona jedynkami
print(np.ones(10, dtype="int64"))        # jak wyżej z okreslonym typem elementow

[1.  1.5 2.  2.5 3.  3.5 4.  4.5] 

[1. 2. 3. 4. 5. 6.] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[ True False False]
 [False  True False]
 [False False  True]] 

[[1 0 0]
 [0 7 0]
 [0 0 9]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[1 1 1 1 1 1 1 1 1 1]


In [14]:
# Operatory - działania zwektoryzowane
# A + B - dodawanie
# A - B - odejmowanie
# A * B - mnozenie
# A / B - dzielenie
# A ** B -  potegowanie
# A // B - dzielenie calkowite
# A % B - reszta z dzielenia
# - A - zmiana znaku
# A > - przyrównanie
# np.log - logarytm
# np.square - kwadrat
# np.sqrt - pierwiastek

n = np.array(np.arange(0,10,1))
s = np.array(np.arange(0,20,2))
print(n,"\n")
print(s,"\n")
print(n+s,"\n")
print(n*s,"\n")
print(0*n,"\n")
print(n+100,"\n")
print(n-s,"\n")
print(n**2,"\n")
print(n>5,"\n")
print(np.log(n),"\n")
print(np.square(n),"\n")
print(np.sqrt(n),"\n")

[0 1 2 3 4 5 6 7 8 9] 

[ 0  2  4  6  8 10 12 14 16 18] 

[ 0  3  6  9 12 15 18 21 24 27] 

[  0   2   8  18  32  50  72  98 128 162] 

[0 0 0 0 0 0 0 0 0 0] 

[100 101 102 103 104 105 106 107 108 109] 

[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9] 

[ 0  1  4  9 16 25 36 49 64 81] 

[False False False False False False  True  True  True  True] 

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458] 

[ 0  1  4  9 16 25 36 49 64 81] 

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 



/home/adsum/.local/lib/python3.6/site-packages/ipykernel_launcher.py:26: RuntimeWarning: divide by zero encountered in log


In [18]:
# Macierze o elementach bedacych liczbami pseudolosowymi

print(np.random.rand(3,4),"\n")          # rozklad jednostajny na przedziale od 0 do 1
print(np.random.randn(3,4),"\n")         # rozklad normalny standardowy

# Powtarzanie wartosci

print(np.repeat("a",5),"\n")             # powtarza 5 razy napis "a"
print(np.repeat([1,2,1],4),"\n")
print(np.repeat([1,2,3],(2,3,4)),"\n")
print(np.repeat([[1,2],[3,4]],(4,5),axis = 1),"\n")    # axis = 1 - kolumna
print(np.repeat([[1,2],[3,4]],(4,5),axis = 0),"\n")    # axis = 0 - wiersz
print(np.tile("a",5),"\n")

[[0.67261186 0.16013947 0.43445166 0.86957366]
 [0.01294772 0.61467653 0.59314477 0.79239341]
 [0.04054275 0.70405706 0.15933217 0.59396923]] 

[[ 0.01055508 -0.89380136  0.16580312 -0.7271138 ]
 [-0.52214797 -1.05238236 -2.06840119 -1.17478761]
 [ 0.15778972 -2.08602551  0.92918329 -0.77205263]] 

['a' 'a' 'a' 'a' 'a'] 

[1 1 1 1 2 2 2 2 1 1 1 1] 

[1 1 2 2 2 3 3 3 3] 

[[1 1 1 1 2 2 2 2 2]
 [3 3 3 3 4 4 4 4 4]] 

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]
 [3 4]
 [3 4]] 

['a' 'a' 'a' 'a' 'a'] 



In [19]:
# Operacje na tablicach

print(np.append(np.array([1,2,2]),0.4),"\n")       # dodanie elementu do tablicy, wynik zawsze w postaci wektora

L = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.append(L,np.tile(0.5,(3,1)),axis = 1),"\n")   # nowa kolumna
print(np.append(L,np.tile(0.5,(1,3)),axis = 0),"\n")   # nowy wiersz
print(np.concatenate((A,L),axis=0),"\n")               # laczenie macierzy
print(np.row_stack((L,[1,2,3])),"\n")
print(np.column_stack((L,[1,2,3])),"\n")

print(np.insert(L,[1],[9],axis = 1),"\n")             # po pierwszej kolumnie wstawia kolumne 9
print(np.insert(L,[1],[9],axis = 0),"\n")             # po pierwszym wierszu wstawia wiersz 9

# Obiekt r_

print(np.r_[1,1,4],"\n")
print(np.r_[1,[1]*5,4],"\n")
print(np.r_[1:4],"\n")
print(np.r_[1:4:0.5],"\n")

[1.  2.  2.  0.4] 

[[1.  2.  3.  0.5]
 [4.  5.  6.  0.5]
 [7.  8.  9.  0.5]] 

[[1.  2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]
 [0.5 0.5 0.5]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]] 

[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]] 

[[1 9 2 3]
 [4 9 5 6]
 [7 9 8 9]] 

[[1 2 3]
 [9 9 9]
 [4 5 6]
 [7 8 9]] 

[1 1 4] 

[1 1 1 1 1 1 4] 

[1 2 3] 

[1.  1.5 2.  2.5 3.  3.5] 



In [28]:
# Uwaga: Algebraiczne mnozenie macierzy - funkcja dot()

M = np.array([[1,2,3],[4,5,5]])
print(M,"\n")
print(M.T,"\n")               # transpozycja macierzy M czyli zamiana kolumn na wiersze

print(np.dot(M,M.T),"\n")

[[1 2 3]
 [4 5 5]] 

[[1 4]
 [2 5]
 [3 5]] 

[[14 29]
 [29 66]] 



In [29]:
# Skumulowana suma i roznica elementow tablicy

print(np.cumsum(s),"\n") # w przypadku macierzy axis = 0 dla wiersza i axis = 1 dla kolumny
print(np.diff(s),"\n")

[ 0  2  6 12 20 30 42 56 72 90] 

[2 2 2 2 2 2 2 2 2] 



In [20]:
# Indeksowanie tablic

x = np.array([2,5,8,3,5,5,6,7,8,9])
A = np.array([[1,2,4],[1,1,5],[1,3,2],[2,5,9],[2,6,7],[2,7,1]])

print(A,"\n")
print(x,"\n")

print(x[4],"\t",x[-1],"\n")             # piaty i ostatni element wektora
print(x[2:7:2],"\n")                    # wybieramy elementy od 2 do 7(bez ostatniego) oddalone od siebie o 2
print(x[2::2],"\n")
print(x[:7:2],"\n")
print(x[[0,2,3,7]],"\n")                     # indeksowanie wektorem
print(x[[True,True,False,False,True,True,False,False,False,True]],"\n") # indeksowanie wektorem logicznym

# Zwektoryzowane operatory relacyjne i logiczne. Operatory relacyjne bez zmian.
# Operatory logiczne:
# a | b - alternatywa
# a & b - koniunkcja
# ~ a   - negacja
# Operatory relacyjne maja nizszy priorytet niz logiczne, nalezy pamietac o nawiasach

print(x[x % 2 == 0],"\n")                   # wybranie elementow o wartosciach parzystych

for index , wiersz in enumerate(A):
    print(index,":",wiersz,end="\n")

print(A[3],"\n")                           # trzeci wiersz
print(A[3][0],"\n")                        # zerowy element trzeciego wiersza

print(A[(3,0)],"\n")                       # inna metoda (mozna pominac ()) - zerowy element trzeciego wiersza

print(A[0:3:1,:],"\n")                     # pierwsze trzy wiersze
print(A[:,2:4:1],"\n")                     # trzecia kolumna
print(A[2:5,:3],"\n")                      # wiersze 2,3,4 i wszystkie kolumny

print(A[np.ix_([0,1],[1,2])],"\n")         # wybieramy 0 i 1 wiersz oraz 1 i 2 kolumne

# Wyszukiwanie numerow indeksow elementow spelniajacych dany warunek

print(np.nonzero(x == 5),"\n")             # numery indeksow ktorych elementy maja wartosc 5
print(np.nonzero(A == 1),"\n")             # numery indeksow ktorych elementy maja wartosc 1
print(np.where(x == 2),"\n")

[[1 2 3]
 [4 5 5]
 [1 0 9]] 

[[1 4 1]
 [2 5 0]
 [3 5 9]] 

[[14 29 28]
 [29 66 49]
 [28 49 82]] 

[ 0  2  6 12 20 30 42 56 72 90] 

[2 2 2 2 2 2 2 2 2] 

[[1 2 4]
 [1 1 5]
 [1 3 2]
 [2 5 9]
 [2 6 7]
 [2 7 1]] 

[2 5 8 3 5 5 6 7 8 9] 

5 	 9 

[8 5 6] 

[8 5 6 8] 

[2 8 5 6] 

[2 8 3 7] 

[2 5 5 5 9] 

[2 8 6 8] 

0 : [1 2 4]
1 : [1 1 5]
2 : [1 3 2]
3 : [2 5 9]
4 : [2 6 7]
5 : [2 7 1]
[2 5 9] 

2 

2 

[[1 2 4]
 [1 1 5]
 [1 3 2]] 

[[4]
 [5]
 [2]
 [9]
 [7]
 [1]] 

[[1 3 2]
 [2 5 9]
 [2 6 7]] 

[[2 4]
 [1 5]] 

(array([1, 4, 5]),) 

(array([0, 1, 1, 2, 5]), array([0, 0, 1, 0, 2])) 

(array([0]),) 

